"""
State and data model definitions for the REACHY lesson planner.

This module defines the Pydantic models and TypedDict structures used to represent
lesson plans, plan segments, and the state of the lesson planning graph/workflow.
These structures ensure type safety and validation for lesson content generated by the AI system.
"""
from __future__ import annotations
from typing import List, TypedDict, Literal
from pydantic import BaseModel, Field
from typing import List, TypedDict, Any, Dict

class PlanSegment(BaseModel):
    """
    Represents a single segment or section within a lesson plan.
    
    Each segment is a discrete unit of instruction with its own script, duration,
    and associated robot behaviors (emotions and motions). Segments are combined
    to form a complete LessonPlan.
    """
    # Title/name of this segment
    title: str
    # Duration in seconds (default 3 minutes)
    duration_sec: int = 180
    # The script/text that the robot should speak during this segment
    script: str
    # A comprehension check question to verify student understanding
    check_question: str
    # The emotional expression the robot should display (e.g., happy, curious, serious)
    emotion: Literal["neutral","happy","curious","encouraging","serious"] = "neutral"
    # The physical gesture or body motion the robot should perform
    motion: Literal["idle","nod","shake_head","look_at_student","celebrate","think"] = "idle"
    # List of source document references used to generate this segment
    sources: List[str] = Field(default_factory=list)

class LessonPlan(BaseModel):
    """
    Represents a complete, structured lesson plan for the REACHY robot.
    
    A lesson plan is composed of multiple PlanSegment objects and contains
    metadata about the lesson's topic, objectives, and the next recommended lesson.
    This is the primary output of the lesson planning system.
    """
    # Unique identifier for this lesson
    lesson_id: str
    # Title/name of the lesson
    title: str
    # List of learning objectives or goals for this lesson
    objectives: List[str]
    # List of PlanSegment objects that make up the lesson content
    segments: List[PlanSegment]
    # Suggestion for which lesson to teach after this one (for curriculum guidance)
    next_lesson_hint: str

from pydantic import BaseModel, Field
from typing import List, Dict, Any

class QuizQuestion(BaseModel):
    question: str
    ideal_answer: str
    rubric_points: List[str] = Field(default_factory=list)
    sources: List[str] = Field(default_factory=list)  # chunk_id list

class QuizResult(BaseModel):
    total_score: int
    max_score: int
    per_question: List[Dict[str, Any]] = Field(default_factory=list)
    feedback: str

class LessonSummary(BaseModel):
    lesson_id: str
    lesson_title: str
    student_id: str
    session_id: str

    duration_minutes: int = 15
    key_takeaways: List[str] = Field(default_factory=list)
    vocabulary: List[Dict[str, str]] = Field(default_factory=list)  # [{"term": "...", "definition": "..."}]
    strengths: List[str] = Field(default_factory=list)
    improvements: List[str] = Field(default_factory=list)
    recommended_next_step: str

    score: int | None = None
    score_max: int | None = None


class GraphState(TypedDict, total=False):
    # inputs
    pdf_paths: List[str]
    topic: str
    student_id: str
    lesson_id: str

    # planner output
    retrieved: list
    lesson_plan_json: str

    # teaching/session
    session_id: str
    segment_index: int
    transcript: List[dict]

    # control flags
    done: bool

    score: int | None
    score_max: int | None

    retrieved: list
    quiz: List[dict]
    student_answers: List[str]
    quiz_result: dict

    lesson_summary: dict

