"""
State and data model definitions for the REACHY lesson planner.

This module defines the Pydantic models and TypedDict structures used to represent
lesson plans, plan segments, and the state of the lesson planning graph/workflow.
These structures ensure type safety and validation for lesson content generated by the AI system.
"""
from __future__ import annotations
from typing import List, TypedDict, Literal
from pydantic import BaseModel, Field

class PlanSegment(BaseModel):
    """
    Represents a single segment or section within a lesson plan.
    
    Each segment is a discrete unit of instruction with its own script, duration,
    and associated robot behaviors (emotions and motions). Segments are combined
    to form a complete LessonPlan.
    """
    # Title/name of this segment
    title: str
    # Duration in seconds (default 3 minutes)
    duration_sec: int = 180
    # The script/text that the robot should speak during this segment
    script: str
    # A comprehension check question to verify student understanding
    check_question: str
    # The emotional expression the robot should display (e.g., happy, curious, serious)
    emotion: Literal["neutral","happy","curious","encouraging","serious"] = "neutral"
    # The physical gesture or body motion the robot should perform
    motion: Literal["idle","nod","shake_head","look_at_student","celebrate","think"] = "idle"
    # List of source document references used to generate this segment
    sources: List[str] = Field(default_factory=list)

class LessonPlan(BaseModel):
    """
    Represents a complete, structured lesson plan for the REACHY robot.
    
    A lesson plan is composed of multiple PlanSegment objects and contains
    metadata about the lesson's topic, objectives, and the next recommended lesson.
    This is the primary output of the lesson planning system.
    """
    # Unique identifier for this lesson
    lesson_id: str
    # Title/name of the lesson
    title: str
    # List of learning objectives or goals for this lesson
    objectives: List[str]
    # List of PlanSegment objects that make up the lesson content
    segments: List[PlanSegment]
    # Suggestion for which lesson to teach after this one (for curriculum guidance)
    next_lesson_hint: str

class GraphState(TypedDict, total=False):
    """
    Represents the state dictionary passed through the lesson planning workflow/graph.
    
    This TypedDict defines all the state variables that flow through the AI agent graph
    during lesson plan generation. The 'total=False' parameter makes all fields optional,
    allowing state to be built incrementally as the workflow progresses.
    """
    # List of file paths to PDF documents used as source material for the lesson
    pdf_paths: List[str]
    # The main topic or subject matter for the lesson to be generated
    topic: str
    # Retrieved content/search results from the knowledge base or documents (used in RAG)
    retrieved: list
    # The generated lesson plan as a JSON string (final output of the workflow)
    lesson_plan_json: str
